import type { AlertRaised } from "@driftcube/shared";

function countMatches(source: string, pattern: RegExp): number {
  return source.match(pattern)?.length ?? 0;
}

function dummyTokenHits(source: string): string[] {
  const matches = [
    { token: "placeholder", pattern: /\bplaceholder\b/gi },
    { token: "todo", pattern: /\bTODO\b/g },
    { token: "tbd", pattern: /\bTBD\b/gi },
    { token: "example", pattern: /\bexample\b/gi },
    { token: "mock", pattern: /\bmock\b/gi },
    { token: "lorem ipsum", pattern: /\blorem ipsum\b/gi },
    { token: "coming soon", pattern: /\bcoming soon\b/gi },
  ]
    .map((entry) => ({
      token: entry.token,
      count: countMatches(source, entry.pattern),
    }))
    .filter((entry) => entry.count > 0)
    .sort((left, right) => right.count - left.count);

  return matches.slice(0, 3).map((entry) => `${entry.token} x${entry.count}`);
}

function cssSignals(source: string): string[] {
  const hits: string[] = [];
  const importantCount = countMatches(source, /!important/gi);
  if (importantCount >= 3) {
    hits.push(`!important x${importantCount}`);
  }

  const largeZ = source.match(/z-index\s*:\s*(\d+)/gi) ?? [];
  if (largeZ.some((item) => Number(item.replace(/[^\d]/g, "")) >= 1000)) {
    hits.push("z-index >= 1000");
  }

  if (/\.placeholder|#placeholder|skeleton|shim/gi.test(source)) {
    hits.push("placeholder styling");
  }

  return [...hits, ...dummyTokenHits(source)].slice(0, 4);
}

function jsonSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }

  if (/"(password|token|secret)"\s*:\s*"(123456|changeme|test|example)"/i.test(source)) {
    hits.push("fake credential value");
  }

  return hits.slice(0, 4);
}

function markdownSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/generated by|copy here|fill this in|write content here/i.test(source)) {
    hits.push("template residue");
  }

  if (/```[\s\S]*TODO[\s\S]*```/i.test(source)) {
    hits.push("todo in code block");
  }

  return hits.slice(0, 4);
}

function yamlSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/\bimage:\s*.+:latest\b/i.test(source)) {
    hits.push("mutable image tag latest");
  }
  if (/\b(host|url|endpoint):\s*https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }
  if (/\b(password|token|secret|apiKey):\s*(changeme|example|test|placeholder|123456)\b/i.test(source)) {
    hits.push("fake secret placeholder");
  }

  return hits.slice(0, 4);
}

function htmlSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/<title>.*(todo|placeholder|coming soon).*<\/title>/i.test(source)) {
    hits.push("placeholder document title");
  }
  if (/\b(id|class)=["'][^"']*(placeholder|mock|demo|test)[^"']*["']/i.test(source)) {
    hits.push("placeholder markup hooks");
  }
  if (/https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }

  return hits.slice(0, 4);
}

function configSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/\b(debug|devMode|mockMode)\s*[:=]\s*(true|1|yes)\b/i.test(source)) {
    hits.push("debug mode enabled");
  }
  if (/\b(password|token|secret|apikey|api_key)\s*[:=]\s*(changeme|example|test|placeholder|123456)\b/i.test(source)) {
    hits.push("fake secret placeholder");
  }
  if (/\b(url|host|endpoint)\s*[:=]\s*https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }

  return hits.slice(0, 4);
}

function xmlSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/<(mock|placeholder|demo|test)[^>]*>/i.test(source) || /\b(id|name)=["'][^"']*(mock|placeholder|demo|test)[^"']*["']/i.test(source)) {
    hits.push("placeholder xml nodes");
  }
  if (/https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }
  if (/<!--[\s\S]*(todo|placeholder|tbd)[\s\S]*-->/i.test(source)) {
    hits.push("template comment residue");
  }

  return hits.slice(0, 4);
}

function dockerfileSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/^from\s+\S+:latest\s*$/im.test(source)) {
    hits.push("base image latest");
  }
  if (/^\s*user\s+root\s*$/im.test(source)) {
    hits.push("container runs as root");
  }
  if (/curl\s+[^|\n]+?\|\s*(sh|bash)/i.test(source) || /wget\s+[^|\n]+?\|\s*(sh|bash)/i.test(source)) {
    hits.push("pipe-to-shell install");
  }
  if (/^\s*env\s+\w+=(changeme|example|test|placeholder|123456)\s*$/im.test(source)) {
    hits.push("fake env placeholder");
  }

  return hits.slice(0, 4);
}

function workflowSignals(source: string): string[] {
  const hits = dummyTokenHits(source);
  if (/\buses:\s*[^@\n]+@(main|master|latest)\b/i.test(source)) {
    hits.push("unpinned action ref");
  }
  if (/\bcontinue-on-error:\s*true\b/i.test(source)) {
    hits.push("continue-on-error true");
  }
  if (/\b(url|host|endpoint):\s*https?:\/\/(localhost|127\.0\.0\.1|example\.com)/i.test(source)) {
    hits.push("local/example endpoint");
  }
  if (/\b(debug|mock|placeholder)\b/i.test(source)) {
    hits.push("workflow placeholder residue");
  }

  return hits.slice(0, 4);
}

function heuristicCategory(language: string, drivers: string[]): string {
  const normalized = drivers.map((driver) => driver.toLowerCase());

  if (normalized.some((driver) => driver.includes("fake secret") || driver.includes("fake credential"))) {
    return "SECRET_PLACEHOLDER";
  }

  if (normalized.some((driver) => driver.includes("local/example endpoint"))) {
    return "LOCAL_ENDPOINT";
  }

  if (normalized.some((driver) => driver.includes("debug mode enabled"))) {
    return "DEBUG_CONFIG";
  }

  if (normalized.some((driver) => driver.includes("unpinned action ref") || driver.includes("continue-on-error"))) {
    return "WORKFLOW_RISK";
  }

  if (normalized.some((driver) => driver.includes("base image latest") || driver.includes("container runs as root") || driver.includes("pipe-to-shell"))) {
    return "CONTAINER_RISK";
  }

  if (normalized.some((driver) => driver.includes("!important") || driver.includes("z-index") || driver.includes("styling"))) {
    return "STYLING_OVERRIDE";
  }

  if (normalized.some((driver) => driver.includes("placeholder") || driver.includes("template") || driver.includes("todo"))) {
    return "PLACEHOLDER_CONTENT";
  }

  if (language === "workflow") {
    return "WORKFLOW_DRIFT";
  }

  if (language === "dockerfile") {
    return "CONTAINER_DRIFT";
  }

  return "CONTENT_DRIFT";
}

export function scanContentHeuristics(input: {
  repoId: string;
  commitSha: string;
  at: string;
  filePath: string;
  language: string;
  source: string;
}): AlertRaised[] {
  const drivers = input.language === "css" || input.language === "scss"
    ? cssSignals(input.source)
    : input.language === "json"
      ? jsonSignals(input.source)
      : input.language === "markdown"
        ? markdownSignals(input.source)
        : input.language === "yaml"
          ? yamlSignals(input.source)
          : input.language === "html"
            ? htmlSignals(input.source)
            : input.language === "xml"
              ? xmlSignals(input.source)
              : input.language === "dockerfile"
                ? dockerfileSignals(input.source)
                : input.language === "workflow"
                  ? workflowSignals(input.source)
            : input.language === "toml" || input.language === "config"
              ? configSignals(input.source)
        : [];

  if (drivers.length === 0) {
    return [];
  }

  const severity = drivers.length >= 3 ? "error" : "warn";
  const category = heuristicCategory(input.language, drivers);

  return [{
    schemaVersion: 1,
    repoId: input.repoId,
    commitSha: input.commitSha,
    at: input.at,
    severity,
    type: "CONTENT_HEURISTIC",
    title: `Non-code content drift detected in ${input.filePath}`,
    evidence: {
      filePath: input.filePath,
      heuristicCategory: category,
      heuristicDrivers: drivers,
      metrics: {
        heuristic_hits: drivers.length,
      },
    },
    recommendation: `Review unsupported artifact changes in ${input.filePath}: ${drivers.join(", ")}.`,
  }];
}
